language: cpp

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode10.2
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/MacKernelSDK
      - xcodebuild -configuration Debug
      - xcodebuild -jobs 1 -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: JvbQ55oB3yZ8w17lQjrAr2Hzhfh1fuDE1hMcljXXb1MEy6pxiSmfX5uLDKVnpFb63khEbm3crs+hrwuXEibqYGjfSgeXtn3YMw237Ye/rmKMtNMJBkXhTwaBFA4leUfXmpN9cAu6e/Agux2leuT7cYV7OmriHGFqqmKPwkXnmcNSNqsucfG1ng97bP28YhMNORrAPDWGI648AfZSe9DdRvP3fjuSRoP2x4fs7jT2ZhspAmcSwfG0UmY4tTNUeHY+0rTgkd9AER7dmwwLZ1loOgOJjM2mnVIjd8Jj8ARAdMSS9Lt9MW+MjRcf82bszRPn/hz9mpLh0Y3rXdGaP+xP2GcLikVoVZHJ7xeJgURfkWHSwC/VaKtEWq8g/A0lLA+/C4oqRjtuQRJkdy8HdA9ZCJMxDrEo67vbX7vlHd50uCnYzM8t4PuiEUOCpDYxGi8b5wDVQnUhL0W9xLKlnK4PKKxJ3ENke+uJp5B3dV9uTJfgc/1vVhmx+fcN9OqebCKKMurqWM3QixKuKl3H7YwBAjjXpeyhvQ7u7cCe9dpeVRXWDb1+53CP4UxtrNLanWa7qgC6sYYheAN96hT9KKSR7Uil/wdJwoRQLLn3HE1s0VDpDm56T/8PQ5z0E7vr0c1B+fAJ3+CIrGb9UTMJo3pNSF6cYih51Bule3URNncF1Cg=
      on:
        tags: true

  - os: osx
    name: "Analyze Clang"
    osx_image: xcode11
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/MacKernelSDK
      - xcodebuild analyze -quiet -scheme VoodooInput -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme VoodooInput -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
